# Generated by Django 5.0.14 on 2026-02-06 18:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20)),
                ('es_principal', models.BooleanField(default=False, help_text='¿Es el almacén central del proyecto?')),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almacenes', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'unique_together': {('proyecto', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('INGRESO_COMPRA', 'Ingreso por Compra'), ('SALIDA_OBRA', 'Salida a Obra (Consumo Torre)'), ('SALIDA_OFICINA', 'Salida a Oficina/Gasto'), ('TRANSFERENCIA_SALIDA', 'Transferencia (Salida)'), ('TRANSFERENCIA_ENTRADA', 'Transferencia (Entrada)'), ('DEVOLUCION_OBRA', 'Reingreso por Devolución de Obra'), ('AJUSTE_INVENTARIO', 'Ajuste de Inventario')], max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('documento_referencia', models.CharField(help_text='Nro Guía, Factura, Vale', max_length=50)),
                ('solicitante', models.CharField(blank=True, max_length=100)),
                ('observacion', models.TextField(blank=True)),
                ('almacen_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='logistica.almacen')),
                ('almacen_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='logistica.almacen')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='proyectos.proyecto')),
                ('torre_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='proyectos.torre')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMovimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.material')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='logistica.movimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('costo_promedio', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('ultimo_costo_compra', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('stock_total_proyecto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias_proyecto', to='catalogo.material')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencias', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Existencia (Costo/Stock Global)',
                'verbose_name_plural': 'Existencias (Costos/Stocks)',
                'unique_together': {('proyecto', 'material')},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ubicacion_pasillo', models.CharField(blank=True, help_text='Ej: Estante A1', max_length=50)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='logistica.almacen')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_almacen', to='catalogo.material')),
            ],
            options={
                'verbose_name': 'Stock Físico',
                'unique_together': {('almacen', 'material')},
            },
        ),
    ]
