# Generated by Django 5.0.14 on 2026-02-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado (Procesado)'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20),
        ),
    ]
