# Generated by Django 5.0.14 on 2026-02-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_movimiento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='nota_ingreso',
            field=models.CharField(blank=True, help_text='Correlativo interno autogenerado', max_length=20, null=True, verbose_name='Nota de Ingreso'),
        ),
    ]
