# Generated by Django 5.0.14 on 2026-02-07 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0004_inventario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
