# Generated by Django 5.0.14 on 2026-02-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0005_delete_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='cantidad_minima',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Punto de reorden (Alerta)', max_digits=12),
        ),
    ]
