# Generated by Django 5.0.14 on 2026-02-07 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0007_requerimiento_detallerequerimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='requerimiento',
            field=models.ForeignKey(blank=True, help_text='Requerimiento aprobado que justifica esta salida', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='logistica.requerimiento'),
        ),
    ]
