# Generated by Django 5.0.14 on 2026-02-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0008_movimiento_requerimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerequerimiento',
            name='cantidad_ingresada',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad recibida en almacén (Compras)', max_digits=12),
        ),
    ]
