# Generated by Django 5.0.14 on 2026-02-10 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0009_detallerequerimiento_cantidad_ingresada'),
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='trabajador',
            field=models.ForeignKey(blank=True, help_text='Trabajador que recibe el EPP', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_epp', to='rrhh.trabajador'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('INGRESO_COMPRA', 'Ingreso por Compra'), ('SALIDA_OBRA', 'Salida a Obra (Consumo Torre)'), ('SALIDA_EPP', 'Entrega de EPP / Ropa'), ('SALIDA_OFICINA', 'Salida a Oficina/Gasto'), ('TRANSFERENCIA_SALIDA', 'Transferencia (Salida)'), ('TRANSFERENCIA_ENTRADA', 'Transferencia (Entrada)'), ('DEVOLUCION_OBRA', 'Reingreso por Devolución de Obra'), ('AJUSTE_INVENTARIO', 'Ajuste de Inventario')], max_length=30),
        ),
    ]
