# Generated by Django 5.0.14 on 2026-02-12 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0010_movimiento_trabajador_alter_movimiento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemovimiento',
            name='requerimiento',
            field=models.ForeignKey(blank=True, help_text='Si se especifica, esta línea atiende/ingresa a este requerimiento específico.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_movimiento_asignados', to='logistica.requerimiento'),
        ),
    ]
