# Generated by Django 5.0.14 on 2026-02-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0011_detallemovimiento_requerimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemovimiento',
            name='es_stock_libre',
            field=models.BooleanField(default=False, help_text='Si es True, evita la asignación automática (FIFO) y entra como stock libre.'),
        ),
    ]
