# Generated by Django 5.0.14 on 2026-02-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0012_detallemovimiento_es_stock_libre'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemovimiento',
            name='series_temporales',
            field=models.TextField(blank=True, help_text='Series separadas por coma para activos fijos (Solo Ingresos)'),
        ),
    ]
