# Generated by Django 5.0.14 on 2026-02-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0013_detallemovimiento_series_temporales'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemovimiento',
            name='marca',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marca/Modelo'),
        ),
    ]
