# Generated by Django 5.0.14 on 2026-02-14 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0003_kit_activo_kit'),
        ('logistica', '0014_detallemovimiento_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemovimiento',
            name='activo',
            field=models.ForeignKey(blank=True, help_text='Activo fijo específico entregado (Solo para Salidas)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='activos.activo'),
        ),
    ]
