# Generated by Django 5.0.14 on 2026-02-14 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0015_detallemovimiento_activo'),
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='solicitante',
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='trabajador',
            field=models.ForeignKey(blank=True, help_text='Trabajador solicitante o beneficiario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='rrhh.trabajador'),
        ),
    ]
