# Generated by Django 5.0.14 on 2026-02-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0016_remove_movimiento_solicitante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('INGRESO_COMPRA', 'Ingreso por Compra'), ('SALIDA_OBRA', 'Salida a Obra (Consumo Torre)'), ('SALIDA_EPP', 'Entrega de EPP / Ropa'), ('SALIDA_OFICINA', 'Salida a Oficina/Gasto'), ('TRANSFERENCIA_SALIDA', 'Transferencia (Salida)'), ('TRANSFERENCIA_ENTRADA', 'Transferencia (Entrada)'), ('DEVOLUCION_OBRA', 'Reingreso por Devolución de Obra'), ('DEVOLUCION_LIMA', 'Devolución a Sede Central (Salida)'), ('REINGRESO_LIMA', 'Reingreso de Sede Central (Entrada)'), ('AJUSTE_INVENTARIO', 'Ajuste de Inventario')], max_length=30),
        ),
    ]
