# Generated by Django 5.0.14 on 2026-02-18 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_proveedor'),
        ('logistica', '0017_alter_movimiento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor (Solo para Ingresos por Compra)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='catalogo.proveedor'),
        ),
    ]
