# Generated by Django 5.0.14 on 2026-02-10 16:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(help_text='Código Interno (Ej: TAL-01)', max_length=50, unique=True)),
                ('serie', models.CharField(blank=True, help_text='Serie del Fabricante', max_length=100)),
                ('nombre', models.CharField(help_text='Ej: Taladro Percutor', max_length=100)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ASIGNADO', 'Asignado (En uso)'), ('MANTENIMIENTO', 'En Mantenimiento'), ('BAJA', 'Dado de Baja')], default='DISPONIBLE', max_length=20)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('valor_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('trabajador_asignado', models.ForeignKey(blank=True, help_text='Quién lo tiene actualmente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_actuales', to='rrhh.trabajador')),
            ],
            options={
                'verbose_name': 'Activo Fijo',
                'verbose_name_plural': 'Activos Fijos',
            },
        ),
        migrations.CreateModel(
            name='AsignacionActivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('observacion_entrega', models.TextField(blank=True)),
                ('observacion_devolucion', models.TextField(blank=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_asignaciones', to='activos.activo')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_activos', to='rrhh.trabajador')),
            ],
        ),
    ]
