# Generated by Django 5.0.14 on 2026-02-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto referencial del equipo', null=True, upload_to='activos/'),
        ),
    ]
