# Generated by Django 5.0.14 on 2026-02-10 23:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_activo_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(help_text='Ej: KIT-01', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Ej: Kit de Herramientas Básicas', max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Kit de Herramientas',
                'verbose_name_plural': 'Kits de Herramientas',
            },
        ),
        migrations.AddField(
            model_name='activo',
            name='kit',
            field=models.ForeignKey(blank=True, help_text='Si pertenece a un kit, se asignará junto con él.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='componentes', to='activos.kit'),
        ),
    ]
