# Generated by Django 5.0.14 on 2026-02-14 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0003_kit_activo_kit'),
        ('logistica', '0016_remove_movimiento_solicitante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='ingreso_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos_generados', to='logistica.movimiento'),
        ),
    ]
