# Generated by Django 5.0.14 on 2026-02-14 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_activo_ingreso_origen'),
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Enlace al catálogo para control de stock', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos_fijos', to='catalogo.material'),
        ),
    ]
