# Generated by Django 5.0.14 on 2026-02-14 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_activo_material'),
        ('logistica', '0016_remove_movimiento_solicitante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='ubicacion',
            field=models.ForeignKey(blank=True, help_text='Almacén físico donde se encuentra actualmente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_en_ubicacion', to='logistica.almacen'),
        ),
    ]
