# Generated by Django 5.0.14 on 2026-02-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0006_activo_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ASIGNADO', 'Asignado (En uso)'), ('EN_TRANSITO', 'En Tránsito / Transferencia'), ('MANTENIMIENTO', 'En Mantenimiento'), ('DEVUELTO_EXTERNO', 'Devuelto a Sede Central/Externo'), ('BAJA', 'Dado de Baja')], default='DISPONIBLE', max_length=20),
        ),
    ]
