# Generated by Django 5.0.14 on 2026-02-10 16:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('talla_zapato', models.CharField(blank=True, help_text='Ej: 40, 42', max_length=10)),
                ('talla_ropa', models.CharField(blank=True, help_text='Ej: M, L, XL', max_length=10)),
                ('activo', models.BooleanField(default=True, help_text='¿Sigue trabajando en la empresa?')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
            },
        ),
    ]
