# Generated by Django 5.0.14 on 2026-02-14 05:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('logistica', '0016_remove_movimiento_solicitante_and_more'),
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaEPP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.material')),
                ('movimiento_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_epp', to='logistica.movimiento')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epps_entregados', to='rrhh.trabajador')),
            ],
            options={
                'verbose_name': 'Historial de EPP',
                'verbose_name_plural': 'Historial de EPPs',
                'ordering': ['-fecha_entrega'],
            },
        ),
    ]
