# Generated by Django 5.0.14 on 2026-02-06 17:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ej: Línea de Transmisión 500kV Mantaro', max_length=200)),
                ('codigo', models.CharField(help_text='Código interno, Ej: LT-500', max_length=20, unique=True)),
                ('usa_control_costos', models.BooleanField(default=True, help_text='Si está activo, el sistema exigirá precios en las compras y calculará el PMP.', verbose_name='¿Controlar Costos?')),
                ('moneda', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares')], default='PEN', max_length=3)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Tramo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ej: Tramo Km 0-20', max_length=100)),
                ('codigo', models.CharField(max_length=20)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos', to='proyectos.proyecto')),
            ],
            options={
                'unique_together': {('proyecto', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Torre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(help_text='Número o código de torre/estructura', max_length=20)),
                ('tipo', models.CharField(choices=[('SUSPENSION', 'Suspensión (Soporta peso)'), ('ANCLAJE', 'Anclaje (Soporta tensión)'), ('REMATE', 'Remate (Inicio/Fin)'), ('OFICINA', 'Oficina / Campamento'), ('OTROS', 'Otros Frentes')], max_length=20)),
                ('ubicacion_gps', models.CharField(blank=True, help_text='Latitud, Longitud', max_length=100, null=True)),
                ('tramo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='torres', to='proyectos.tramo')),
            ],
            options={
                'ordering': ['codigo'],
                'unique_together': {('tramo', 'codigo')},
            },
        ),
    ]
