# Generated by Django 5.0.14 on 2026-02-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='Mi Empresa S.A.C.', max_length=200)),
                ('ruc', models.CharField(blank=True, help_text='RUC de la empresa', max_length=11)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='Logo para reportes (Recomendado: 300x100px)', null=True, upload_to='empresa/')),
            ],
            options={
                'verbose_name': 'Configuración General',
                'verbose_name_plural': 'Configuración General',
            },
        ),
    ]
