# Generated by Django 5.0.14 on 2026-02-18 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracion'),
        ('logistica', '0018_movimiento_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almacenes', models.ManyToManyField(blank=True, help_text='Almacenes a los que tiene acceso este usuario.', related_name='usuarios_permitidos', to='logistica.almacen')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
