# Generated by Django 5.0.14 on 2026-02-06 17:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(help_text='Ej: ELE, FER, EPP', max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(help_text='Código único global. Ej: MAT-001', max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('unidad_medida', models.CharField(help_text='UND, M, KG, BLS', max_length=10)),
                ('tipo', models.CharField(choices=[('CONSUMIBLE', 'Consumible (Cemento, Pernos)'), ('ACTIVO_FIJO', 'Activo Fijo (Taladros, Equipos)'), ('EPP', 'EPP (Cascos, Guantes)')], default='CONSUMIBLE', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales', to='catalogo.categoria')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['codigo'],
            },
        ),
    ]
